-- Database schema for Consensus & Voting (Milestone 5)
-- SQLite schema for proposal and vote persistence

-- Proposals table
-- Stores all proposals created during agent conversations
CREATE TABLE IF NOT EXISTS proposals (
  id TEXT PRIMARY KEY,                  -- UUID generated by VoteManager
  roomId TEXT NOT NULL,                 -- Room where proposal was created
  title TEXT NOT NULL,                  -- Short title of the proposal
  description TEXT NOT NULL,            -- Full description of what's being proposed
  proposerId TEXT NOT NULL,             -- Agent ID who created the proposal
  proposerName TEXT NOT NULL,           -- Agent name who created the proposal
  threshold REAL NOT NULL DEFAULT 0.5,  -- Approval threshold (0.0 to 1.0)
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  createdAt INTEGER NOT NULL,           -- Unix timestamp (milliseconds)
  resolvedAt INTEGER,                   -- Unix timestamp when resolved (NULL if pending)

  -- Constraints
  CHECK (threshold >= 0.0 AND threshold <= 1.0),
  CHECK (status IN ('pending', 'approved', 'rejected'))
);

-- Votes table
-- Stores individual votes cast by agents on proposals
CREATE TABLE IF NOT EXISTS votes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  proposalId TEXT NOT NULL,             -- Foreign key to proposals.id
  agentId TEXT NOT NULL,                -- Agent ID who cast the vote
  agentName TEXT NOT NULL,              -- Agent name who cast the vote
  voteType TEXT NOT NULL,               -- 'yes', 'no', 'abstain'
  rationale TEXT,                       -- Optional explanation for the vote
  timestamp INTEGER NOT NULL,           -- Unix timestamp (milliseconds)

  -- Foreign key constraint
  FOREIGN KEY (proposalId) REFERENCES proposals(id) ON DELETE CASCADE,

  -- Constraints
  CHECK (voteType IN ('yes', 'no', 'abstain')),

  -- Ensure each agent can only vote once per proposal
  UNIQUE(proposalId, agentId)
);

-- Messages table
-- Stores all conversation messages for full history tracking
CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  roomId TEXT NOT NULL,                 -- Room where message was sent
  agentId TEXT NOT NULL,                -- Agent ID who sent the message
  agentName TEXT NOT NULL,              -- Agent name who sent the message
  role TEXT NOT NULL,                   -- Agent role (architect, critic, etc.)
  content TEXT NOT NULL,                -- Message content
  timestamp INTEGER NOT NULL,           -- Unix timestamp (milliseconds)

  -- Index on roomId for efficient room-based queries
  -- Index on timestamp for chronological ordering
  CHECK (length(content) > 0)
);

-- Indexes for efficient querying

-- Index for finding proposals by room
CREATE INDEX IF NOT EXISTS idx_proposals_roomId
ON proposals(roomId);

-- Index for finding proposals by status
CREATE INDEX IF NOT EXISTS idx_proposals_status
ON proposals(status);

-- Index for finding proposals by creation time (for chronological queries)
CREATE INDEX IF NOT EXISTS idx_proposals_createdAt
ON proposals(createdAt DESC);

-- Index for finding votes by proposal (most common query)
CREATE INDEX IF NOT EXISTS idx_votes_proposalId
ON votes(proposalId);

-- Index for finding votes by agent
CREATE INDEX IF NOT EXISTS idx_votes_agentId
ON votes(agentId);

-- Index for finding votes by timestamp (for chronological queries)
CREATE INDEX IF NOT EXISTS idx_votes_timestamp
ON votes(timestamp DESC);

-- Compound index for efficient proposal+agent lookups
CREATE INDEX IF NOT EXISTS idx_votes_proposal_agent
ON votes(proposalId, agentId);

-- Index for finding messages by room (most common query)
CREATE INDEX IF NOT EXISTS idx_messages_roomId
ON messages(roomId);

-- Index for finding messages by timestamp (chronological queries)
CREATE INDEX IF NOT EXISTS idx_messages_timestamp
ON messages(timestamp DESC);

-- Index for finding messages by agent
CREATE INDEX IF NOT EXISTS idx_messages_agentId
ON messages(agentId);

-- Compound index for efficient room+timestamp lookups (pagination)
CREATE INDEX IF NOT EXISTS idx_messages_room_timestamp
ON messages(roomId, timestamp DESC);

-- Agent Metadata table
-- Stores comprehensive agent metadata for discovery and analytics
CREATE TABLE IF NOT EXISTS agent_metadata (
  agentId TEXT NOT NULL,                    -- Agent ID
  roomId TEXT NOT NULL,                     -- Room where agent is/was present
  agentName TEXT NOT NULL,                  -- Agent display name
  type TEXT NOT NULL,                       -- 'human', 'ai', 'hybrid'
  role TEXT NOT NULL,                       -- Agent role (architect, critic, etc.)
  version TEXT,                             -- Optional agent software version
  capabilities TEXT NOT NULL,               -- JSON array of capabilities
  llmConfig TEXT,                           -- Optional JSON object with LLM configuration
  personality TEXT,                         -- Optional JSON object with personality traits
  systemPromptSummary TEXT,                 -- Optional truncated system prompt (max 200 chars)
  custom TEXT,                              -- Optional JSON object for custom metadata
  createdAt INTEGER NOT NULL,               -- Unix timestamp (milliseconds)
  lastUpdatedAt INTEGER NOT NULL,           -- Unix timestamp (milliseconds)

  -- Primary key is combination of agentId and roomId
  -- An agent can have different metadata in different rooms
  PRIMARY KEY (agentId, roomId),

  -- Constraints
  CHECK (type IN ('human', 'ai', 'hybrid')),
  CHECK (length(systemPromptSummary) <= 200 OR systemPromptSummary IS NULL)
);

-- Index for finding metadata by room (common query)
CREATE INDEX IF NOT EXISTS idx_agent_metadata_roomId
ON agent_metadata(roomId);

-- Index for finding metadata by agent type
CREATE INDEX IF NOT EXISTS idx_agent_metadata_type
ON agent_metadata(type);

-- Index for finding metadata by role
CREATE INDEX IF NOT EXISTS idx_agent_metadata_role
ON agent_metadata(role);

-- Index for chronological queries
CREATE INDEX IF NOT EXISTS idx_agent_metadata_lastUpdatedAt
ON agent_metadata(lastUpdatedAt DESC);
